# Generated by Django 3.2.6 on 2025-11-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('estadoActual', models.CharField(choices=[('Transito', 'Transito'), ('Alistamiento', 'Alistamiento'), ('Por Verificar', 'Por Verificar'), ('Rechazado por Verificar', 'Rehazado X Verificar'), ('Verificado', 'Verificado'), ('Creado', 'Creado'), ('Empacado por Despachar', 'Empacadp X Despachar'), ('Despachado', 'Despachado'), ('Despachado por Facturar', 'Despachado X Facturar'), ('Facturado', 'Facturado'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Produccion', 'Produccion'), ('Bordado', 'Bordado'), ('Dropshipping', 'Dropshipping'), ('Compra', 'Compra'), ('Anulado', 'Anulado')], default='Alistamiento', max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('owner_id', models.CharField(db_index=True, editable=False, max_length=128)),
            ],
        ),
    ]
